"""GitHub operations — PR create, merge, close via gh CLI."""
from taghdev.worker.tasks.git_ops import run_exec


async def create_pr(
    repo: str, branch: str, base: str, title: str, body: str
) -> tuple[str, int]:
    """Create a GitHub PR. Returns (url, number)."""
    pr_url = await run_exec(
        "gh", "pr", "create", "--repo", repo, "--head", branch, "--base", base,
        "--title", title, "--body", body,
    )
    pr_url = pr_url.strip()

    pr_num_str = await run_exec(
        "gh", "pr", "view", branch, "--repo", repo, "--json", "number", "-q", ".number",
    )
    pr_number = int(pr_num_str.strip())

    return pr_url, pr_number


async def merge_pr(repo: str, pr_number: int):
    """Merge a PR with squash."""
    await run_exec("gh", "pr", "merge", str(pr_number), "--repo", repo, "--squash", "--admin")


async def close_pr(repo: str, pr_number: int):
    """Close a PR without merging."""
    await run_exec("gh", "pr", "close", str(pr_number), "--repo", repo)


async def delete_branch(repo: str, branch: str):
    """Delete a remote branch."""
    await run_exec(
        "gh", "api", f"repos/{repo}/git/refs/heads/{branch}", "-X", "DELETE",
        ignore_errors=True,
    )


def generate_pr_body(task) -> str:
    """Generate a PR description from task details."""
    return (
        f"## Task\n{task.description}\n\n"
        f"## Details\n"
        f"- **Project:** {task.project.name}\n"
        f"- **Requested by:** @{task.user.telegram_username or task.user.telegram_id}\n"
        f"- **Agent turns:** {task.agent_turns or 'N/A'}\n\n"
        f"---\n"
        f"Generated by [THAG GROUP](https://github.com/taghdev)"
    )
