// AUTOGENERATED — do not edit by hand.
//
// Source: specs/001-per-chat-instances/contracts/stream-events.schema.json
// Generator: scripts/codegen/gen_stream_event_types.py
//
// To refresh: `python scripts/codegen/gen_stream_event_types.py`
// CI runs `--check` and fails if this file drifts from the schema.
//
// Discriminated union over `type`. Use it like:
//
//   function handle(evt: StreamEvent) {
//     switch (evt.type) {
//       case "message_id":     ...
//       case "tool_use":       ...
//       case "instance_failed": ...
//       default: const _exh: never = evt; throw new Error(_exh);
//     }
//   }
//
// The `never` arm makes the switch exhaustive at compile time.
// Adding a new event to the schema breaks the type checker until
// every consumer adds a matching case — exactly the gate the
// stream-events drift bug needed.


/** A single button on a card. `action_id` either looks like `<verb>:<id>` (the chat-text protocol the assistant_endpoint switch matches on) OR an internal `link` URL the frontend follows directly. */
export interface CardAction {
  label: string;
  action_id?: string;
  link?: string;
  style?: "primary" | "danger" | "secondary";
}

/** Persistence anchor. Emitted exactly once at the start of every assistant turn so the frontend can tie streamed deltas to the saved message row. */
export interface MessageId {
  type: "message_id";
  /** WebChatMessage.id, stringified. */
  id: string;
}

/** Agent invoked an MCP tool. Frontend surfaces these as a thinking-step chip. */
export interface ToolUse {
  type: "tool_use";
  /** Anthropic tool_use_id. */
  id: string;
  /** Human-readable tool name (e.g. `git_status`). */
  tool: string;
  /** Optional truncated input preview. */
  input?: string;
  status?: "running" | "complete" | "error";
}

/** Tool returned. Principle IV: `content` MUST run through `audit_service.redact()` before this event is emitted; the redactor-coverage fitness function asserts this. */
export interface ToolResult {
  type: "tool_result";
  tool_use_id: string;
  /** Redacted tool output, truncated to 1500 chars. */
  content: string;
  is_error?: boolean;
  status?: "complete" | "error";
}

/** T070 — Container-mode chat is bringing up its instance. Frontend renders a non-blocking starting-up banner. ETA is the SC-002 cold-path budget. */
export interface InstanceProvisioning {
  type: "instance_provisioning";
  slug: string;
  estimated_seconds: number;
}

/** T080 — Instance reached terminal `failed` state. Frontend renders a card with Retry + Main Menu actions per CLAUDE.md No Dead Ends. The optional `message` carries the per-failure-code prose `_failure_chat_copy` previously injected into the LLM's text channel — now structured so the UI owns the rendering. */
export interface InstanceFailed {
  type: "instance_failed";
  slug: string;
  failure_code: "image_build" | "compose_up" | "projctl_up" | "tunnel_provision" | "dns" | "health_check" | "oom" | "storage_full" | "orchestrator_crash" | "unknown";
  /** Human-readable failure copy from `_failure_chat_copy(failure_code, failure_message)`. Frontend renders this as the card body. */
  message?: string;
  actions: CardAction[];
}

export interface PerUserCapVariant {
  type: "instance_limit_exceeded";
  variant: "per_user_cap";
  cap: number;
  active_chat_ids: number[];
  instances_endpoint: string;
  actions: CardAction[];
}

export interface PlatformCapacityVariant {
  type: "instance_limit_exceeded";
  variant: "platform_capacity";
  retry_after_s: number;
}

/** T084 — Per-message poll of the Redis upstream-state cache. Renders a non-blocking pill in the chat. FR-027a strict: instance status NEVER flipped to `failed` regardless. */
export interface InstanceUpstreamDegraded {
  type: "instance_upstream_degraded";
  slug: string;
  /** Map of capability name (e.g. preview_url) to upstream identifier (e.g. cloudflare). */
  capabilities: Record<string, string>;
}

/** T037a — A second concurrent message hit the per-instance lock and could not acquire it within the patience window. Frontend shows an amber pill, no destructive UX. */
export interface InstanceBusy {
  type: "instance_busy";
  slug: string;
}

/** T073 — User confirmed end-session. Frontend shows a teardown indicator; instance row will flip to `destroyed` on the worker job's completion. */
export interface InstanceTerminating {
  type: "instance_terminating";
  slug: string;
}

/** T080 — User tapped Retry on a failed-provision card. Frontend shows a green pill while the new provision is in-flight. */
export interface InstanceRetryStarted {
  type: "instance_retry_started";
  failed_instance_id: string;
}

/** Generic two-step destructive-confirm prompt. Frontend renders ConfirmCard with Cancel mandatory (CLAUDE.md No Dead Ends). */
export interface Confirm {
  type: "confirm";
  prompt: string;
  actions: CardAction[];
}

/** Short orchestrator-level error surfaced to the chat — empty message, invalid retry target, no-active-instance, unhandled exception, etc. The frontend renders this as a small inline error card with proper styling rather than letting the orchestrator inject prose into the LLM's text channel (Principle II: deterministic infra status flows through structured events, not impersonated LLM voice). */
export interface OrchestratorError {
  type: "error";
  message: string;
}

/** Every event the backend may emit on the assistant_stream `2:` channel. */
export type StreamEvent =
  | MessageId
  | ToolUse
  | ToolResult
  | InstanceProvisioning
  | InstanceFailed
  | PerUserCapVariant
  | PlatformCapacityVariant
  | InstanceUpstreamDegraded
  | InstanceBusy
  | InstanceTerminating
  | InstanceRetryStarted
  | Confirm
  | OrchestratorError;

/** Closed set of event-type discriminators. Mirrors the schema enum. */
export const STREAM_EVENT_TYPES = ["message_id", "tool_use", "tool_result", "instance_provisioning", "instance_failed", "instance_limit_exceeded", "instance_upstream_degraded", "instance_busy", "instance_terminating", "instance_retry_started", "confirm", "error"] as const;
export type StreamEventType = (typeof STREAM_EVENT_TYPES)[number];
