// AUTOGENERATED by the TAGH platform overlay — do not edit by hand.
//
// What this file does:
//   The browser hits the Vite dev server through Cloudflare:
//     https://${INSTANCE_HMR_HOST}/@vite/client
//   For Laravel + laravel-vite-plugin, the URL written to public/hot
//   becomes the prefix for every <script> / <link> tag the @vite()
//   blade directive emits. By default Vite writes its bind address
//   (http://0.0.0.0:5173) — which is unreachable from the user's
//   browser. The fix is `server.origin`.
//
// Why a wrapper instead of editing the project's vite.config.ts:
//   * The project owns its plugins / aliases / optimizeDeps. We must
//     NOT clobber them — only add the server-side bits the platform
//     needs to make assets browser-reachable through the tunnel.
//   * mergeConfig from Vite is the canonical way to compose configs.
//   * The wrapper is overlay-shaped: regenerated on every provision,
//     never hand-edited. Spec 002 (deferred) replaces this with a
//     full project-owned manifest + platform overlay split.
//
// Generated for INSTANCE_HOST=${INSTANCE_HOST}, INSTANCE_HMR_HOST=${INSTANCE_HMR_HOST}.

import { defineConfig, mergeConfig } from 'vite';

// Resolve the project's own Vite config — try .ts first (modern), fall
// back to .js. The dynamic import keeps every plugin (vue, laravel-
// vite-plugin, etc.) and resolve-alias the project ships.
const projectConfigModule = await import('./vite.config.ts').catch(
  () => import('./vite.config.js'),
);
const projectExport = projectConfigModule.default;
const projectConfig =
  typeof projectExport === 'function'
    ? await projectExport({ command: 'serve', mode: 'development' })
    : projectExport;

const overlay = defineConfig({
  server: {
    host: '0.0.0.0',
    port: 5173,
    strictPort: true,
    // The KEY fix — laravel-vite-plugin reads the resolved Vite
    // server config and writes `server.origin` (or falls back to
    // host:port) to public/hot. Setting it to the public HMR URL
    // means @vite() blade tags emit script srcs the browser can
    // reach through Cloudflare.
    origin: 'https://${INSTANCE_HMR_HOST}',
    hmr: {
      // HMR WebSocket: browser connects to wss://INSTANCE_HMR_HOST:443,
      // Cloudflare terminates TLS and cloudflared forwards to node:5173.
      host: '${INSTANCE_HMR_HOST}',
      clientPort: 443,
      protocol: 'wss',
    },
    // CORS: the HTML loads from https://INSTANCE_HOST but the script
    // tags reference https://INSTANCE_HMR_HOST — that's cross-origin.
    // Without explicit CORS, Vite returns ACAO=server.origin (the HMR
    // host) which doesn't match the requesting web origin → browser
    // blocks the JS/CSS even though the bytes were 200 OK. Allow
    // both origins so the @vite() <script> tags execute.
    cors: {
      origin: [
        'https://${INSTANCE_HOST}',
        'https://${INSTANCE_HMR_HOST}',
      ],
      credentials: true,
    },
    // Vite refuses requests whose Host header isn't here. Both the
    // main web origin and the hmr origin are valid approach paths.
    allowedHosts: ['${INSTANCE_HOST}', '${INSTANCE_HMR_HOST}'],
  },
});

export default mergeConfig(projectConfig, overlay);
