// AUTOGENERATED by the TAGH platform overlay — do not edit by hand.
//
// What this file does:
//   The browser hits the Vite dev server through Cloudflare:
//     https://${INSTANCE_HMR_HOST}/@vite/client
//   For Laravel + laravel-vite-plugin, the URL written to public/hot
//   becomes the prefix for every <script> / <link> tag the @vite()
//   blade directive emits. By default Vite writes its bind address
//   (http://0.0.0.0:5173) — which is unreachable from the user's
//   browser. The fix is `server.origin`.
//
// Why a wrapper instead of editing the project's vite.config.ts:
//   * The project owns its plugins / aliases / optimizeDeps. We must
//     NOT clobber them — only add the server-side bits the platform
//     needs to make assets browser-reachable through the tunnel.
//   * mergeConfig from Vite is the canonical way to compose configs.
//   * The wrapper is overlay-shaped: regenerated on every provision,
//     never hand-edited. Spec 002 (deferred) replaces this with a
//     full project-owned manifest + platform overlay split.
//
// Generated for INSTANCE_HOST=${INSTANCE_HOST}, INSTANCE_HMR_HOST=${INSTANCE_HMR_HOST}.

import { defineConfig, loadConfigFromFile, mergeConfig } from 'vite';
import { existsSync } from 'node:fs';
import { resolve as pathResolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));

// Resolve the project's own Vite config so its plugins (laravel-vite-
// plugin, @vitejs/plugin-vue, vuetify, …) and aliases survive the
// merge. We can't `await import('./vite.config.ts')` because Node's
// native ESM loader has no TypeScript transformer — the import throws
// ERR_MODULE_NOT_FOUND, the fallback hits a non-existent .js file,
// and `mergeConfig(undefined, overlay)` quietly drops the project's
// plugins. Vite still boots (the overlay is a valid config) but
// laravel-vite-plugin never runs, so public/hot is never written and
// every Laravel page 500s with ViteManifestNotFoundException.
//
// Vite ships `loadConfigFromFile` for exactly this case: it bundles
// the candidate file with esbuild on the fly so .ts / .js / .mjs
// all work uniformly.
async function loadProjectConfig() {
  for (const candidate of ['vite.config.ts', 'vite.config.js', 'vite.config.mjs']) {
    const abs = pathResolve(__dirname, candidate);
    if (!existsSync(abs)) continue;
    try {
      const result = await loadConfigFromFile(
        { command: 'serve', mode: 'development' },
        abs,
      );
      if (result?.config) {
        console.log(`[tagh] loaded project config from ${candidate}`);
        return result.config;
      }
    } catch (err) {
      console.warn(`[tagh] failed to load ${candidate}: ${err?.message || err}`);
    }
  }
  console.warn('[tagh] no project vite config found — overlay-only fallback (laravel-vite-plugin will NOT run)');
  return {};
}

const projectConfig = await loadProjectConfig();

const overlay = defineConfig({
  // Override expensive optimizeDeps settings that some project configs
  // ship (Vuexy / Vuetify templates often set `force: true` and a wide
  // `entries: ["./resources/ts/**/*.vue"]`). On every container
  // restart Vite would then re-scan thousands of .vue files in
  // parallel via esbuild workers — peak anon-rss hit 3.77 GB on
  // staging and OOM-killed esbuild before the dev server could
  // serve a single request. We want the persistent cache to survive
  // restarts, not be invalidated every boot.
  optimizeDeps: {
    force: false,
    holdUntilCrawlEnd: false,
  },
  server: {
    host: '0.0.0.0',
    port: 5173,
    strictPort: true,
    // The KEY fix — laravel-vite-plugin reads the resolved Vite
    // server config and writes `server.origin` (or falls back to
    // host:port) to public/hot. Setting it to the public HMR URL
    // means @vite() blade tags emit script srcs the browser can
    // reach through Cloudflare.
    origin: 'https://${INSTANCE_HMR_HOST}',
    hmr: {
      // HMR WebSocket: browser connects to wss://INSTANCE_HMR_HOST:443,
      // Cloudflare terminates TLS and cloudflared forwards to node:5173.
      host: '${INSTANCE_HMR_HOST}',
      clientPort: 443,
      protocol: 'wss',
    },
    // CORS: the HTML loads from INSTANCE_HOST but the script tags
    // reference INSTANCE_HMR_HOST — that's cross-origin. Without
    // explicit CORS, Vite returns ACAO=server.origin which doesn't
    // match the requesting web origin → browser blocks JS/CSS even
    // though the bytes were 200 OK. Allow BOTH protocols (http +
    // https) for both hostnames so a user who landed on http://
    // (because they typed it, or before Cloudflare's "Always use
    // HTTPS" rewrites) still gets working assets. The cloudflared
    // tunnel terminates TLS at the edge regardless.
    cors: {
      origin: [
        'https://${INSTANCE_HOST}',
        'http://${INSTANCE_HOST}',
        'https://${INSTANCE_HMR_HOST}',
        'http://${INSTANCE_HMR_HOST}',
      ],
      credentials: true,
    },
    // Vite refuses requests whose Host header isn't here. Both the
    // main web origin and the hmr origin are valid approach paths.
    allowedHosts: ['${INSTANCE_HOST}', '${INSTANCE_HMR_HOST}'],
  },
});

export default mergeConfig(projectConfig, overlay);
