"""GitHub git provider — uses gh CLI."""
from typing import Any

from openclow.providers.base import GitProvider
from openclow.providers.registry import register_git
from openclow.worker.tasks.git_ops import run_exec


@register_git("github")
class GitHubProvider(GitProvider):
    def __init__(self, config: dict):
        self.token = config.get("token", "")

    async def clone_repo(self, repo: str, dest: str) -> None:
        # Use token for auth (private repos + avoids username prompt)
        if self.token:
            await run_exec("git", "clone", f"https://x-access-token:{self.token}@github.com/{repo}.git", dest)
        else:
            await run_exec("git", "clone", f"https://github.com/{repo}.git", dest)

    async def create_pr(
        self, repo: str, branch: str, base: str, title: str, body: str
    ) -> tuple[str, int]:
        pr_url = await run_exec(
            "gh", "pr", "create", "--repo", repo, "--head", branch, "--base", base,
            "--title", title, "--body", body,
        )
        pr_url = pr_url.strip()

        pr_num_str = await run_exec(
            "gh", "pr", "view", branch, "--repo", repo, "--json", "number", "-q", ".number",
        )
        return pr_url, int(pr_num_str.strip())

    async def merge_pr(self, repo: str, pr_number: int) -> None:
        await run_exec("gh", "pr", "merge", str(pr_number), "--repo", repo, "--squash", "--admin")

    async def close_pr(self, repo: str, pr_number: int) -> None:
        await run_exec("gh", "pr", "close", str(pr_number), "--repo", repo)

    async def delete_branch(self, repo: str, branch: str) -> None:
        await run_exec(
            "gh", "api", f"repos/{repo}/git/refs/heads/{branch}", "-X", "DELETE",
            ignore_errors=True,
        )

    def generate_pr_body(self, task: Any) -> str:
        return (
            f"## Task\n{task.description}\n\n"
            f"## Details\n"
            f"- **Project:** {task.project.name}\n"
            f"- **Agent turns:** {task.agent_turns or 'N/A'}\n\n"
            f"---\n"
            f"Generated by [THAG GROUP](https://github.com/openclow)"
        )
