#!/usr/bin/env python
"""Generate chat_frontend/src/types/stream-events.ts from the JSON Schema.

Single source of truth: ``specs/001-per-chat-instances/contracts/stream-events.schema.json``.

Why hand-roll a generator instead of pulling in ``quicktype``:

  * One contract surface, ~10 events. The generator is ~150 lines vs
    a multi-MB Node dependency.
  * We need exact control over the discriminated-union shape so the
    frontend's ``parseStream`` reducer is exhaustive at compile time
    (TypeScript ``never`` check on the default branch).
  * The schema is project-internal — no need for a vendor's general
    representation.

Idempotent: emit-then-diff. CI runs this with ``--check`` and fails if
the generated file is stale.

Usage:
  python scripts/codegen/gen_stream_event_types.py            # rewrite
  python scripts/codegen/gen_stream_event_types.py --check    # CI gate
"""
from __future__ import annotations

import json
import pathlib
import sys
from typing import Any


REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
SCHEMA = REPO_ROOT / "specs" / "001-per-chat-instances" / "contracts" / "stream-events.schema.json"
OUT = REPO_ROOT / "chat_frontend" / "src" / "types" / "stream-events.ts"

HEADER = """// AUTOGENERATED — do not edit by hand.
//
// Source: specs/001-per-chat-instances/contracts/stream-events.schema.json
// Generator: scripts/codegen/gen_stream_event_types.py
//
// To refresh: `python scripts/codegen/gen_stream_event_types.py`
// CI runs `--check` and fails if this file drifts from the schema.
//
// Discriminated union over `type`. Use it like:
//
//   function handle(evt: StreamEvent) {
//     switch (evt.type) {
//       case "message_id":     ...
//       case "tool_use":       ...
//       case "instance_failed": ...
//       default: const _exh: never = evt; throw new Error(_exh);
//     }
//   }
//
// The `never` arm makes the switch exhaustive at compile time.
// Adding a new event to the schema breaks the type checker until
// every consumer adds a matching case — exactly the gate the
// stream-events drift bug needed.

"""


def _ts_type_for(prop: dict[str, Any]) -> str:
    """Map one JSON-Schema property node to a TypeScript type."""
    if "const" in prop:
        return f'"{prop["const"]}"' if isinstance(prop["const"], str) else json.dumps(prop["const"])
    if "enum" in prop:
        return " | ".join(json.dumps(v) for v in prop["enum"])
    t = prop.get("type")
    if t == "string":
        return "string"
    if t == "integer":
        return "number"
    if t == "number":
        return "number"
    if t == "boolean":
        return "boolean"
    if t == "array":
        items = prop.get("items", {})
        if "$ref" in items:
            return f"{_ref_to_name(items['$ref'])}[]"
        return f"{_ts_type_for(items)}[]"
    if t == "object":
        if prop.get("additionalProperties"):
            ap = prop["additionalProperties"]
            return f"Record<string, {_ts_type_for(ap)}>"
        return "Record<string, unknown>"
    if "$ref" in prop:
        return _ref_to_name(prop["$ref"])
    return "unknown"


def _ref_to_name(ref: str) -> str:
    # `#/$defs/CardAction` → `CardAction`
    return ref.split("/")[-1]


def _emit_object(name: str, schema: dict[str, Any]) -> str:
    """Emit a TS interface for an object schema."""
    required = set(schema.get("required") or [])
    properties = schema.get("properties") or {}
    lines = [f"export interface {name} {{"]
    for prop_name, prop in properties.items():
        opt = "" if prop_name in required else "?"
        ts = _ts_type_for(prop)
        # JSDoc for description
        if "description" in prop:
            lines.append(f"  /** {prop['description']} */")
        lines.append(f"  {prop_name}{opt}: {ts};")
    lines.append("}")
    return "\n".join(lines)


def _branch_name(branch: dict[str, Any], idx: int) -> str:
    """Pick a TS interface name for one oneOf branch."""
    return branch.get("title") or f"StreamEventVariant{idx}"


def _flatten_oneof(branch: dict[str, Any]) -> list[dict[str, Any]]:
    """If a branch is itself a oneOf, return its sub-branches; else [branch]."""
    if "oneOf" in branch:
        return branch["oneOf"]
    return [branch]


def render() -> str:
    schema = json.loads(SCHEMA.read_text(encoding="utf-8"))
    parts: list[str] = [HEADER]

    # 1. Shared $defs first.
    for def_name, def_schema in (schema.get("$defs") or {}).items():
        if "description" in def_schema:
            parts.append(f"/** {def_schema['description']} */")
        parts.append(_emit_object(def_name, def_schema))
        parts.append("")

    # 2. One interface per oneOf branch (flattened).
    branch_names: list[str] = []
    for idx, branch in enumerate(schema["oneOf"]):
        for sub in _flatten_oneof(branch):
            name = _branch_name(sub, idx)
            branch_names.append(name)
            if "description" in sub:
                parts.append(f"/** {sub['description']} */")
            parts.append(_emit_object(name, sub))
            parts.append("")

    # 3. The discriminated union.
    parts.append("/** Every event the backend may emit on the assistant_stream `2:` channel. */")
    parts.append(
        "export type StreamEvent =\n  | "
        + "\n  | ".join(branch_names)
        + ";"
    )
    parts.append("")

    # 4. The closed type-string set, useful for runtime discrimination.
    type_enum = schema["properties"]["type"]["enum"]
    parts.append("/** Closed set of event-type discriminators. Mirrors the schema enum. */")
    parts.append(
        "export const STREAM_EVENT_TYPES = ["
        + ", ".join(f'"{t}"' for t in type_enum)
        + "] as const;"
    )
    parts.append("export type StreamEventType = (typeof STREAM_EVENT_TYPES)[number];")
    parts.append("")

    return "\n".join(parts)


def main() -> int:
    check_only = "--check" in sys.argv
    rendered = render()

    OUT.parent.mkdir(parents=True, exist_ok=True)
    if check_only:
        if not OUT.exists():
            print(f"FAIL: {OUT} does not exist; run gen_stream_event_types.py", file=sys.stderr)
            return 1
        existing = OUT.read_text(encoding="utf-8")
        if existing != rendered:
            print(
                f"FAIL: {OUT} is stale relative to the schema. "
                "Run `python scripts/codegen/gen_stream_event_types.py` and commit.",
                file=sys.stderr,
            )
            return 1
        print(f"OK: {OUT.relative_to(REPO_ROOT)} matches the schema.")
        return 0

    OUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO_ROOT)} ({len(rendered)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
